### ISSUE TITLE
Blocked video

### ISSUE THREAD

**Issue by markdrrr** [pillargg/youtube-upload#11]
Blocks all videos I try to download
How to fix it ?
![image](https://user-images.githubusercontent.com/56235826/106082302-7e934200-612b-11eb-9292-17b177dc3658.png)

**Comment by chand1012** [comment]
What was the title of the video? I found that if you make it something like "Test Video" or along those lines it tends to get blocked due to YouTube assuming its spam.

**Comment by UniDima** [comment]
My videos was also blocked. I used different names and descriptions, but every video got banned immediatly after upload

**Comment by chand1012** [comment]
It could be possible that YouTube is blocking many of their API videos
unless you get approval, I know that their API keys are quite restricted
unless you get explicit permission from them. Sadly this is not something I
can fix, and you're going to have to take it up with Google.

**Comment by UniDima** [comment]
I've made a research and found the same. Sadly now you need a verification by google to use some methods. Anyway library works perfect, I've already sent verification request, thank you!
