### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by markdrrr** [pillargg/youtube-upload#9]
Is there any limit on the number of publications per day? 
______
How to add thumbnail not a link but a file?

**Comment by chand1012** [comment]
> 
> 
> Is there any limit on the number of publications per day?
> 
> How to add thumbnail not a link but a file?

The upload limit is imposed by Google, not us. See [here](https://developers.google.com/youtube/v3/getting-started#quota).

We plan on adding functionality for thumbnail uploading in the future, but for now it is via a URL. In theory you could upload the file to some sort of file server, either an S3 bucket or another type of scriptable image upload service (Imgur wouldn't be a bad option), and then get the public URL of the file for the function call.
